<div class="row">
    <div class="form-group col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <?php echo $this->translate->_('Redefinir a senha'); ?>
            </div>
            <div class="panel-body">
                <legend><?php echo $this->translate->_('Informe sua nova senha'); ?></legend>

                <form method="post" action="" id="form">
                    <label class="errors">
                        <?php echo (!empty($this->msg)) ? $this->msg : ''; ?>
                    </label>
                    <div class="form-group col-md-3 col-xs-12">
                        <label><?php echo $this->translate->_('Nova Senha'); ?></label>
                        <input required="required" style="float: left; margin-right: 10px;" type="password" name="senha" class="email-input form-control" />                        
                    </div>
                    <div class="form-group col-md-3 col-xs-12">
                        <label><?php echo $this->translate->_('Confirmar Nova Senha'); ?></label>
                        <input required="required" style="float: left; margin-right: 10px;" type="password" name="confirmar_senha" class="email-input form-control" />
                    </div>
                    <div class="form-group col-md-3 col-xs-12 no-label">
                        <input type="submit" value="<?php echo $this->translate->_('Alterar a senha'); ?>" class="btn btn-espaco no-label" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

