<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/bootstrap-3.1.1/bootstrap-theme.min.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/bootstrap-3.1.1/bootstrap.min.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/ui-bootstrap/jquery-ui-1.8.16.custom.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/js/default/jquery/jquery.treeview/jquery.treeview.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/font-awesome-4.3.0/css/font-awesome.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/js/default/chosen-1.1.0/chosen.css" type="text/css"/>
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/js/default/jquery/datetimepicker-master/jquery.datetimepicker.css" type="text/css"/>
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/geral.css" type="text/css" />