<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/jquery/jquery-1.7.2.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/jquery/jquery-ui-1.8.9.custom.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/bootstrap-3.1.1/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/bootstrap-3.1.1/bootbox.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/jquery/jquery.form.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/admin/jquery.maskedinput.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/jquery/jquery.price_format.1.5.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/jquery/jquery.validate.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/admin/sistemas.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/itarget/expressoes.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/utilidades.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/validation.js"></script>
<!--
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/itarget/janelas.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/jquery/localization/messages_ptbr.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/jquery/datetimepicker-master/jquery.datetimepicker.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/jquery/jquery.f2.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/jquery/jquery.finder_box.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/moeda.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/default-sistema.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/jquery/jquery.cookie.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/sistema-layout.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/jquery/jquery.treeview/jquery.treeview.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/chosen-1.1.0/chosen.jquery.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/php.full.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/jquery/datetimepicker-master/jquery.datetimepicker.js"></script>
-->