<style type="text/css">
    p {line-height: 1.7em}
</style>
<div class="title-form" style="height: 50px">
    <div style="float: left">
        <h2><?php echo $this->translate->_('Regras'); ?></h2>
    </div>
    <div class="clear"></div>
</div>

<div class="conteudo-esquerdo">
    <br clear="all" />
</div>

<div class="conteudo-direito">
    
    <div>
<style type="text/css">
p { margin-bottom: 0.21cm; }</style>
<h2 class="western" style="margin-bottom: 0cm; text-align: center;">
	<strong><font face="Verdana, sans-serif">REGULAMENTO PARA PARTICIPA&Ccedil;&Atilde;O EM EVENTOS &ndash; SAE BRASIL</font></strong></h2>
<p class="western" style="margin-bottom: 0cm; font-weight: normal;">
	&nbsp;</p>
<h2 class="western" style="margin-bottom: 0cm; font-weight: normal;">
	<font face="Verdana, sans-serif">1-Inscri&ccedil;&otilde;es:</font></h2>
<p class="western" style="margin-bottom: 0cm; font-weight: normal;">
	<font face="Verdana, sans-serif">As inscri&ccedil;&otilde;es para os eventos promovidos pela SAE BRASIL poder&atilde;o ser efetuadas:</font></p>
<p class="western" style="margin-bottom: 0cm; font-weight: normal;">
	<font face="Verdana, sans-serif">1.1 Pela internet: o interessado deve acessar o site www.saebrasil.org.br e escolher o evento de interesse, bem como uma das modalidades de pagamento (boleto banc&aacute;rio ou cart&atilde;o de cr&eacute;dito).</font></p>
<p class="western" style="margin-bottom: 0cm;">
	<font face="Verdana, sans-serif"><span style="font-weight: normal;">1.2 As inscri&ccedil;&otilde;es pela internet ficam dispon&iacute;veis at&eacute; dois dias &uacute;teis antes do in&iacute;cio do evento para a op&ccedil;&atilde;o de pagamento por boleto banc&aacute;rio, e at&eacute; um dia &uacute;til antes do in&iacute;cio do evento para cart&otilde;es de cr&eacute;dito.</span></font></p>
<p class="western" style="margin-bottom: 0cm; font-weight: normal;">
	&nbsp;</p>
<h2 class="western" style="margin-bottom: 0cm; font-weight: normal;">
	<font face="Verdana, sans-serif">2-Formas de pagamento pela internet: </font></h2>
<p class="western" style="margin-bottom: 0cm; font-weight: normal;">
	<font face="Verdana, sans-serif"><u>2.1 Boleto banc&aacute;rio:</u></font></p>
<p class="western" style="margin-bottom: 0cm; font-weight: normal;">
	<font face="Verdana, sans-serif">2.1.1 Ao escolher a op&ccedil;&atilde;o &ldquo;boleto banc&aacute;rio&rdquo;, o sistema gerar&aacute; um boleto na tela, que, impresso, poder&aacute; ser pago em qualquer banco ou pelo Internet Banking.</font></p>
<p class="western" style="margin-bottom: 0cm; font-weight: normal;">
	<font face="Verdana, sans-serif">2.1.2 A data de vencimento do boleto ser&aacute; de sete dias ap&oacute;s a pr&eacute;-inscri&ccedil;&atilde;o no evento. Ap&oacute;s esse prazo, o documento perde a validade e, caso ainda haja tempo h&aacute;bil e interesse em participar do evento, o interessado dever&aacute; acessar o Espa&ccedil;o do Congressista atrav&eacute;s de login e senha e reemitir o boleto banc&aacute;rio. </font></p>
<p class="western" style="margin-bottom: 0cm; font-weight: normal;">
	<font face="Verdana, sans-serif">2.1.3 A data de vencimento do boleto banc&aacute;rio nunca ultrapassar&aacute; dois dias &uacute;teis antes do in&iacute;cio do evento. Ser&aacute; regressiva quando faltar seis ou menos dias &uacute;teis para o prazo final de pagamento atrav&eacute;s do boleto (dois dias &uacute;teis).</font></p>
<p class="western" style="margin-bottom: 0cm; font-weight: normal;">
	<font face="Verdana, sans-serif">2.1.4 Caso opte pelo pagamento por boleto banc&aacute;rio, a inscri&ccedil;&atilde;o no evento escolhido ser&aacute; feita ap&oacute;s a confirma&ccedil;&atilde;o do cr&eacute;dito pela institui&ccedil;&atilde;o banc&aacute;ria, que ocorre, geralmente, 24 horas ap&oacute;s o pagamento.</font></p>
<p class="western" style="margin-bottom: 0cm; font-weight: normal;">
	<font face="Verdana, sans-serif">2.1.5 O comprovante de pagamento do boleto banc&aacute;rio dever&aacute; ser apresentado na entrada do evento.</font></p>
<p class="western" style="margin-bottom: 0cm; font-weight: normal;">
	&nbsp;</p>
<p class="western" style="margin-bottom: 0cm; font-weight: normal;">
	<font face="Verdana, sans-serif"><u>2.2 Cart&atilde;o de cr&eacute;dito </u></font></p>
<p class="western" style="margin-bottom: 0cm; font-weight: normal;">
	<font face="Verdana, sans-serif">2.2.1 O pagamento com cart&atilde;o poder&aacute; ser feito em parcelas, de acordo com a informa&ccedil;&atilde;o que consta no site do evento.</font></p>
<p class="western" style="margin-bottom: 0cm; font-weight: normal;">
	&nbsp;</p>
<h2 class="western" style="margin-bottom: 0cm; font-weight: normal;">
	<font face="Verdana, sans-serif">Observa&ccedil;&otilde;es gerais</font></h2>
<p class="western" style="margin-bottom: 0cm;">
	<font face="Verdana, sans-serif"><span style="font-weight: normal;">2.1 A frequ&ecirc;ncia aos eventos &eacute; permitida somente para aqueles regularmente inscritos.</span></font></p>
<p class="western" style="margin-bottom: 0cm;">
	<style type="text/css">
p { margin-bottom: 0.21cm; }	</style>
</p>
<p class="western" style="margin-bottom: 0cm;">
	<font face="Verdana, sans-serif"><span style="font-weight: normal;">2.2 N&atilde;o &eacute; permitida a transfer&ecirc;ncia de inscri&ccedil;&atilde;o para outro evento, sem a previa solicita&ccedil;&atilde;o formal.</span></font></p>
<p class="western" style="margin-bottom: 0cm;">
	<font face="Verdana, sans-serif"><span style="font-weight: normal;">2.3 Em todos os dias do evento, no ato do registro da frequ&ecirc;ncia, ser&aacute; solicitada a identifica&ccedil;&atilde;o do inscrito, que poder&aacute; ser feita por meio de qualquer documento de identidade com fotografia (RG, carteira profissional, CNH, etc.).</span></font></p>
<p class="western" style="margin-bottom: 0cm;">
	<font face="Verdana, sans-serif"><span style="font-weight: normal;">2.4 Observar as informa&ccedil;&otilde;es do Termo de Cancelamento apresentado antes da conclus&atilde;o da inscri&ccedil;&atilde;o.</span></font></p>
<p class="western" style="margin-bottom: 0cm;">
	<font face="Verdana, sans-serif"><span style="font-weight: normal;">2.5 Os casos n&atilde;o previstos neste regulamento ser&atilde;o encaminhados para delibera&ccedil;&atilde;o da SAE BRASIL.</span></font></p>

    </div>

    <label style="cursor: pointer">
        <input type="checkbox" name="termos" value="1" />
        <?php echo $this->translate->_('Concordo com os termos citados acima'); ?>
    </label>

    <div class="local_rodape">
        <input class="ui-corner-all botaoAssociado" type="button" value="<?php echo $this->translate->_('Prosseguir'); ?>" onclick="checkTermos(); void(0);" />
    </div>

</div>
<div class="clear"></div>
<script type="text/javascript">
    function checkTermos() {
        if($("input[name='termos']").is(":checked")) {
            window.location.href = baseUrl + "/inscricao/inscricoes/atividades";
        } else {
            Sistema.alert("<?php echo $this->translate->_('Para prosseguir e necessario concordar os termos das regras'); ?>");
        }
    }
</script>