<div>
    <div class="panel panel-default">
        <div class="panel-heading">
            UNSUBSCRITE OR CANCELLATION
        </div>
        <div class="panel-body" style="max-height: 300px; overflow: auto;text-align: justify; padding: 7px;">
            <p>
                1. In case of failing attendance at the event, the insured may cancel
                the registration according to the following rules:
            </p>

            <p>
                a) With full refund of the registration fee:<br />

                SOLE AND ONLY FOR ENTRIES MADE BY INTERNET, within 7 days of payment,
                provided with at least 48 business hours before the day the event starts,
                by submitting written request to the e-mail eventos@saebrasil.org.br
                requesting the cancellation and the corresponding reimbursement,
                stating the data bank for deposit.
            </p>

            <p>
                b) The total entry fees converted into credit for future use:<br />

                Within 48 hours before the event, by submitting written request to the e-mail
                eventos@saebrasil.org.br requesting the conversion of credit, which should
                be used within 90 days from the date the request. <u>The entry which does not
                forward the request for cancellation and / or does not indicate the event
                that will use the credit within the time mentioned above will forfeit the
                refund / credit.</u>
            </p>

            <p>
                c) The entry which does not attend the event and does not forward the
                request for cancellation and / or does not indicate the event that will use
                the credit within the time mentioned above, will forfeit the refund / credit.
            </p>
            </p>

            <label style="cursor: pointer">
                <input type="checkbox" name="termo_cancelamento" value="true" />
                <?php echo $this->translate->_('Li e aceito o termo de cancelamento.'); ?>
            </label>
        </div>
    </div>
</div>